# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to dev.decryptology.net
        uses: docker/login-action@v3
        with:
          registry: dev.decryptology.net
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            --no-cache
            --pull
          tags: dev.decryptology.net/decryp7/jupyter-docker:latest